### Inserción de un usuario

POST http://localhost:8008/api/v1/clients
Content-Type: application/json
Accept: application/json

{
  "firstName": "Maria",
  "lastName": "Iribarne",
  "birthDate": "1991-04-30T00:00:00.000-0000",
  "status": true
}

###
