GET http://localhost:8008/api/v1/user/
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaXNzIjoiUGlyYXRlQmF5IiwidHlwZSI6IkFVVEhOIiwiZXhwIjoxNTkxMzE5OTYwfQ.gPanGOwGoBrqFQ_rEHwoXpiT_x7ZJwDBxwxb-lW_m-g
Accept: application/json

###
